version: '3'

services:
  databases:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      # - ./schema.sql:/docker-entrypoint-initdb.d/init.sql
      - /Users/armando/SDCDB:/var/lib/postgresql/data
    ports:
      - 5432:5432
  server:
    build: .
    # image: node:12
    volumes:
      - .:/usr/src/app
    ports:
        - "8000:7000"